# All of the errors below are yielded from the "title" service name.
bad_banners = [
    '301 Moved Permanently',
    '400 Bad Request',
    '403 Access Denied',
    '403 Forbidden',
    '404 Not Found',
    '408 Request Timeout',
    '408 Timeout',
    '500 Internal Server Error',
    'Access Denied',
    'Application Server Error',
    'Bad Request',
    'Bad Request (400)',
    'Invalid URL',
    'Error',
    'ERROR: The request could not be satisfied',
    'Fastly error: unknown domain',
    'HTTP 400',
    'Request Timeout',
    'Server Error',
    'Service Unavailable',
    'Welcome to nginx!',
    'Welcome to nginx on Debian!',
]